---
:active_admin: false
:additional_file_patterns: []
:classified_sort: true
:classes_default_to_s: []
:command: 
:debug: false
:exclude_controllers: true
:exclude_factories: true
:exclude_fixtures: true
:exclude_helpers: true
:exclude_scaffolds: true
:exclude_serializers: false
:exclude_sti_subclasses: false
:exclude_tests: true
:force: false
:format_markdown: false
:format_rdoc: false
:format_yard: false
:frozen: false
:hide_default_column_types: 'json,jsonb,hstore'
:hide_limit_column_types: 'integer,bigint,boolean'
:ignore_columns: 
:ignore_model_sub_dir: false
:ignore_routes: 
:ignore_unknown_models: false
:include_version: false
:model_dir:
- app/models
:models: true
:position: before
:position_in_additional_file_patterns: before
:position_in_class: before
:position_in_factory: before
:position_in_fixture: before
:position_in_routes: before
:position_in_serializer: before
:position_in_test: before
:require: []
:root_dir:
- ''
:routes: false
:show_check_constraints: false
:show_complete_foreign_keys: false
:show_foreign_keys: true
:show_indexes: true
:simple_indexes: false
:skip_on_db_migrate: false
:sort: false
:target_action: :do_annotations
:timestamp: false
:timestamp_columns:
- created_at
- updated_at
:trace: false
:with_comment: true
:with_column_comments: true
:with_table_comments: true
:wrapper: 
:wrapper_close: 
:wrapper_open: 
