EnableDefaultLinters: true
exclude:
  - app/views/grants/_activate_form.html.erb
linters:
  ErbSafety:
    enabled: true
    exclude:
      - 'app/views/kaminari/**'
      - 'app/views/admin/transaction.html.erb'
  RequireInputAutocomplete:
    enabled: false
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml

      # |
      # v Rules that tend to be broken/flaky inside views (e.g. Style/FrozenStringLiteralComment)
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      # ^

      Style/MultilineIfModifier:
        Enabled: false
      Layout/ArgumentAlignment:
        Enabled: false
      Naming/VariableNumber:
        Enabled: false
      Style/NegatedUnless:
        Enabled: false
      Style/MultilineTernaryOperator:
        Enabled: false
      Style/NestedTernaryOperator:
        Enabled: false
      Style/StringConcatenation:
        Enabled: false
