require: rubocop-rails
inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'lib/tasks/**/*'
    - 'vendor/**/*'

# The "offical" rubocop style guide is indeed quite strict. So intead, we use
# the Relaxed Ruby Style guide. https://relaxed.ruby.style/

inherit_gem:
  relaxed-rubocop: .rubocop.yml

Style/RedundantSelf:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/FrozenStringLiteralComment:
  Exclude:
    - 'app/views/**/*.jbuilder'

Lint/UselessAssignment:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: ending_only

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/RedundantReturn:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Style/NumericLiterals:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  NumberOfEmptyLines: [1, 2, 3, 4, 5]

Style/CommentedKeyword:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line

Style/RescueModifier:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed
  AllowInnerSlashes: true

Layout/DotPosition:
  Enabled: true

# Layout/CommentIndentation:
#   AllowForAlignment: true # this is erroring

# Metrics/LineLength:
#   Max: 80

Bundler/OrderedGems:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/HashLikeCase:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/ClassAndModuleChildren:
  Exclude:
    - 'config/**/*.rb'
    - 'app/models/ahoy/{event,visit}.rb'

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

Rails/RequestReferer:
  EnforcedStyle: referrer

Rails/ApplicationController:
  Exclude:
    - 'app/controllers/docs/api_controller.rb'
    - 'app/controllers/stripe_controller.rb'
    - 'app/controllers/twilio_controller.rb'
    - 'app/controllers/docuseal_controller.rb'
    - 'app/controllers/column/webhooks_controller.rb'

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/Validation:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false
