# frozen_string_literal: true

# This migration comes from lab_tech (originally 20210205225332)
class AddObservationDiff < ActiveRecord::Migration[5.1]
  def change
    # Give us a place to put diffs generated by, e.g., check_please
    add_column "lab_tech_observations", "diff", :text
  end

end
