# frozen_string_literal: true

module EventMappingEngine
  module EventIds
    INCOMING_FEES = 1671
    HACK_CLUB_BANK = 636
    NOEVENT = 999
    HACKATHON_GRANT_FUND = 1610
    WINTER_HARDWARE_WONDERLAND_GRANT_FUND = 1966
    ARGOSY_GRANT_FUND = 3349
    FIRST_TRANSPARENCY_GRANT_FUND = 1803
    HACK_FOUNDATION_INTEREST = 2740
    REIMBURSEMENT_CLEARING = 4318
    SVB_SWEEPS = 5832
  end
end
